# Generated by Django 3.0.8 on 2020-07-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('nohin_date', models.DateField(verbose_name='納品日')),
                ('nohinsaki', models.CharField(max_length=50, verbose_name='納品先')),
                ('total_price', models.IntegerField(verbose_name='合計金額')),
                ('memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='メモ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suitou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('suitou_date', models.DateField(verbose_name='出納日')),
                ('suitousaki', models.CharField(max_length=50, verbose_name='出納先')),
                ('total_price', models.IntegerField(verbose_name='合計金額')),
                ('memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='メモ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuitouDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('kataban', models.CharField(max_length=50, verbose_name='会社名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('suitou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_table.Suitou', verbose_name='出納')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shohin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('kataban', models.CharField(max_length=50, verbose_name='会社名')),
                ('shohin_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('zaikosu', models.IntegerField(verbose_name='在庫数')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('memo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='メモ')),
            ],
            options={
                'unique_together': {('belong_user', 'kataban')},
            },
        ),
        migrations.CreateModel(
            name='NohinDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('kataban', models.CharField(max_length=50, verbose_name='会社名')),
                ('price', models.IntegerField(verbose_name='単価')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('nohin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_table.Nohin', verbose_name='納品')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_date', models.DateTimeField(verbose_name='登録日時')),
                ('regist_user', models.CharField(max_length=50, verbose_name='登録ユーザ')),
                ('update_date', models.DateTimeField(null=True, verbose_name='更新日時')),
                ('update_user', models.CharField(max_length=50, null=True, verbose_name='更新ユーザ')),
                ('belong_user', models.CharField(max_length=50, verbose_name='所属ユーザ')),
                ('company_name', models.CharField(max_length=50, verbose_name='会社名')),
            ],
            options={
                'unique_together': {('belong_user', 'company_name')},
            },
        ),
    ]
